bookstore/bookstore/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from bookstoreapp.views import *
from category.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookstoreapp/', include('bookstoreapp.urls')),
    path('category/', include('category.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/category/urls.py
from django.urls import path
from .views import welcoming, category_index , category_details, Category_Create, Catergory_Update, delete_category, login_view


urlpatterns = [
    path('cat' , welcoming , name = 'welcoming'),
    path('main', category_index, name = 'category.main'),
    path('create', Category_Create, name = 'category.create'),
    path('<int:id>', category_details, name = 'category.show'),
    path('update/<int:id>', Catergory_Update, name = 'category.update'),
    path('delete/<int:id>', delete_category, name = 'category.delete'),
    path('' , login_view , name='login')
  
]

bookstore/category/models.py
from django.db import models
# Create your models here.
from django.shortcuts import reverse , get_object_or_404    

class Category(models.Model):
    name = models.CharField(max_length=50 , unique=True)
    description = models.CharField(max_length=200 , null=True , blank=True)
    
    def __str__(self):
        return f"{self.name}"
    @classmethod
    def get_all_categories(cls):
        Categories = cls.objects.all()
        return Categories
    @classmethod
    def get_category_by_id(cls, id):
        return get_object_or_404(cls, pk=id)
    @property
    def show_url(self):
        url = reverse('category.show', args=[self.id])
        return url

bookstore/category/forms.py
from django import forms
from category.models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise forms.ValidationError("Please Enter Name.")
        elif len(name) < 2:
            raise forms.ValidationError("Name must be at least 2 characters long.")
        return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if not description:
            raise forms.ValidationError("Please Enter Description.")
        if description and len(description) < 10:
            raise forms.ValidationError("Description must be at least 10 characters long.")
        return description

bookstore/category/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404 , redirect , reverse  
from django.urls import reverse
from django.http import HttpResponse
from .models import Category
from .forms import CategoryForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages


def welcoming (request):
    return HttpResponse("<h1>Welcome to Categories <3 </h1>")
def category_index(request):
    categories = Category.get_all_categories()
    return render(request, 'category/main.html', { 'categories': categories})

def category_details(request, id):
    category = get_object_or_404(Category, id=id)
    return render(request, 'category/show.html', {'category': category})

def Category_Create(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save()
            return redirect('category.main')
        
    return render(request, 'category/create.html', {'form': form})

def Catergory_Update(request, id):
    book = Category.get_category_by_id(id) 
    form = CategoryForm(instance=book)
    
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect('category.main')
    
    return render(request, 'category/edit.html', {'form': form})
    
def delete_category(request, id):
    book = Category.get_category_by_id(id)
    book.delete()
    return redirect('category.main')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.objects.filter(username=username).first()
        if user is not None:
            authenticated_user = authenticate(username=username, password=password)
            if authenticated_user is not None:
                login(request, authenticated_user)
                messages.success(request, 'You have been logged in successfully.')
                return redirect('category.main')
            else:
                messages.error(request, 'Invalid password.')
        else:
            messages.error(request, 'User does not exist.')

    return render(request, 'category/index.html')

bookstore/category/templates/category/create.html
{% extends 'layouts/base.html'%}
{%load static %}
{% block title %} Create Category {%endblock%}

{%block content%}
<div class="container mt-4 w-75 bg-light p-5">
    <h1>Create New Category</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label text-start" for="id_name">Name:</label>
            {{ form.name }}
            {% for error in form.name.errors %}
                <div class="error-message text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            <label class="form-label" for="id_description">Description:</label>
            {{ form.description }}
            {% for error in form.description.errors %}
            <div class="error-message text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('input, textarea, select').forEach(function(input) {
            input.removeAttribute('required');
        });
    });
</script>

{%endblock%}

bookstore/category/templates/category/edit.html
{% extends 'layouts/base.html'%}
{%load static %}
{% block title %} Create Category {%endblock%}

{%block content%}

<h2>Edit Category</h2>
<div class="card w-50 rounded-5 p-5 >
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}  
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </div>
</div>
{%endblock%}

bookstore/category/templates/category/index.html
{% extends 'layouts/base.html'%}
{%load static %}
{% block title %} Login {%endblock%}

{%block content%}

<div class="row justify-content-center mx-auto my-5 w-75">
    <div class="col-md-12">
        <div class="login-form bg-light opacity-25 p-5  rounded-5">
            <h2 class="text-center mb-4 p-3">Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" id="username" name="username" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" id="password" name="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary m-3">Login</button>
            </form>
        </div>
    </div>
</div>


{%endblock%}

bookstore/category/templates/category/main.html
{% extends 'layouts/base.html'%}
{%load static %}

{% block title %}  Categories {%endblock%}

{%block content%}
<h1>Welcome {{user.username}}</h1>

<div class="container-fluid w-75 mt-4">
    <h2 class="p-5">Categories</h2>
    <table class="table category-table rounded-5 text-light px-5" style="background-color: #496989; color: #F1EEDC;">
        <thead class="p-4">
            <tr class="pb-3">
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
                
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td>
                    <a href="{{category.show_url}}" class="btn btn-light text-primary fs-6">Show</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-primary">
        <a href="{% url 'category.create' %}" style="color: #f7efd2;">Add New Category</a>
    </button>
</div>

{%endblock%}

bookstore/category/templates/category/show.html
{% extends 'layouts/base.html'%}
{%load static %}
{% block title %} Create Category {%endblock%}

{%block content%}

<h2 class="mb-4" >Category Details</h2>
<div class="card w-50 rounded-5 p-5">
    <div class="card-body">
        <h5 class="card-title fw-bold fs-4">{{ category.name }}</h5>
        <p class="card-text fs-5">Description: {{ category.description }}</p>
        <form id="delete-form" action="{% url 'category.delete' category.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger m-4">Delete</button>
        </form>
        <a href="{% url 'category.update' category.id %}" class="btn btn-primary m-4">Update</a>
    </div>
</div>

{%endblock%}